version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - twitter-clone-network

  twitter-clone-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: twitter-clone-api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=twitter-clone
    networks:
      - twitter-clone-network

networks:
  twitter-clone-network:
    driver: bridge

volumes:
  mongodb_data:
